title: SCAC - Network Limited

email: say.arts@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  Yubisay

url: "https://yubisay.github.io"

# Build settings
markdown: kramdown

destination: _site

gems:
  - jekyll-feed
  - jekyll-redirect-from

permalink: :title

exclude: ['CNAME', '_config.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html', 'node_modules']
keep_files: ['sftp-config.json', '.htaccess']
include: ['.htaccess']

defaults:
    - scope:
        path: ""
      values:
        layout: "default"

collections:
  africa:
    title: 'Africa'
    output: true
  americas:
    title: 'Americas'
    output: true

prose:
  rooturl: ''
  siteurl: 'http://yubisay.github.io/scac'
  media: 'assets'
  ignore: ['CNAME', '_config.yml', '_config-dev.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html', 'node_modules']
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
