title: "SCAC − Network Limited"

email: say.arts@gmail.com

description: ''
baseurl: ''

url: "https://yubisay.github.io/scac"

permalink: :title

markdown: kramdown

kramdown:
  parse_span_html: true

defaults:
    - scope:
        path: ''
      values:
        layout: "default"

exclude: ['CNAME', '_config.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html', 'node_modules', '*.ico', 'todo.md', '_includes', '_layouts']
keep_files: ['sftp-config.json', '.htaccess']
include: ['.htaccess']

gems:
  - jekyll-redirect-from
  - jekyll-feed

prose:
  rooturl: ''
  siteurl: 'http://yubisay.github.io/scac'
  media: 'assets'
  ignore: ['CNAME', '_config.yml', '_config-dev.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html', 'node_modules', '_includes', '_layouts', 'assets', '*.ico']
  metadata:
    '':
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "Main URL for the page, see <a href='https://jekyllrb.com/docs/permalinks/'>permalinks</a>. It should start and end with /. Only latin chars are allowed."
          type: "text"
          placeholder: "/main-title/"
      - name: "redirect_from"
        field:
          element: "text"
          label: "Redirect URL"
          help: "This URL will redirect to this page"
          type: "text"
          placeholder: "/alternative-title/"
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          help: "Choose post language"
          options:
            - name: 'English'
              value: 'en'
            - name: 'Français'
              value: 'fr'
      - name: "ref"
        field:
          element: "hidden"
          value: "blog"
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          help: "Title tag. Keywords first, < 70 chars, no articles/preps/etc."
          type: "text"
          placeholder: "[Primary Keyword] - Marketing Blog | TTBA Group | Montreal"
      - name: "meta-description"
        field:
          element: "textarea"
          label: "Meta Description"
          help: "Used as description snippet by search engines. < 160 chars"
          placeholder: ""

t:
  en:
    home: "Home"
    about: "About us"
    faq: "FAQ"
    advertising: "Advertise with us"
    contact: "Contact us"
    offers: "Recent offers"
    add-offer: "Add your offer"
    africa: "Africa"
    americas: "Americas"
    asia-pacific: "Asia-Pacific"
    europe: "Europe"
    sitemap: "Site map"
    privacy: "Privacy & jurisdictional clause"
    documentation: "Trade documentation"
    webmaster: "Web Site Administrator"
  fr:
    home: "Home"
    about: "About us"
    faq: "FAQ"
    advertising: "Advertise with us"
    contact: "Contact us"
    offers: "Recent offers"
    add-offer: "Add your offer"
    africa: "Africa"
    americas: "Americas"
    asia-pacific: "Asia-Pacific"
    europe: "Europe"

